### ISSUE TITLE
Proving Grounds error maybe?

### ISSUE THREAD

**Issue by jungheeMW** [DeadlyBossMods/DBM-Challenges#35]
**Describe the bug**
Timer errors for Proving Grounds gold DPS challenge, done in tank spec

**Do you have an error log of what happened?**
[PG gold dps challenge in tank spec.zip](https://github.com/user-attachments/files/16116035/PG.gold.dps.challenge.in.tank.spec.zip)

**Screenshots**
![WoWScrnShot_070524_103914](https://github.com/DeadlyBossMods/DBM-Challenges/assets/134947146/f70c692d-06e8-4afb-b084-af2b29cd8891)
![WoWScrnShot_070524_103954](https://github.com/DeadlyBossMods/DBM-Challenges/assets/134947146/2d6c086f-9eca-42c7-8fb6-9e30411b23ac)
![WoWScrnShot_070524_104041](https://github.com/DeadlyBossMods/DBM-Challenges/assets/134947146/724f6e79-e235-4f04-b5d1-2cbab7c545ec)

**Which version of DeadlyBossMods are you using?**
DBM-Challenges r164

**Comment by MysticalOS** [comment]
so not alpha? cause I fixed some of these already.

actually def not alpha cause every timer was replaced with nameplate timers.

**Comment by jungheeMW** [comment]
Will check back in with an alpha build, probably no errors then.

**Comment by MysticalOS** [comment]
Unless running debugmode, nameplate timers don't generate errors even if they are wrong. Can do /DBM Debug to toggle on if you really want to start generating nameplate timer errors (but be aware that it forces actual timers to start in ADDITION to nameplate timers so it's noisy in M+)

**Comment by jungheeMW** [comment]
I could just turn it on for Proving Grounds and then toggle it off after I'm done.
